version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - frontend
    restart: on-failure

  client:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./client:/app
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    networks:
      - frontend
    restart: on-failure

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
      - ./backend/src:/app/src
      - ./backend/nodemon.json:/app/nodemon.json
    networks:
      - frontend
    restart: on-failure

networks:
  frontend:
