version: "3.8"

services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./stock-market:/app
    networks:
      - frontend
    ports:
      - "80:80"
    restart: on-failure

networks:
  frontend:

